model_list: []
general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL
  store_prompts_in_spend_logs: false
  maximum_spend_logs_retention_period: 7d
litellm_settings:
  request_timeout: 120
  num_retries: 0
